def cat():
    print("    		M.					   .:M")
    print("		MMMM.					.:MMMM")
    print("		MMMMMMMM			     .:MMMMMMM")
    print("		:MMHHHMMMMHMM.	.:MMMMMMMMM:.	   .:MMHHMHMM:")
    print("		 :MMHHIIIHMMMM.:MMHHHHIIIHHMMMM. .:MMHIHIIHHM:")
    print("		  MMMHIIIIHHMMMIIHHMHHIIIIIHHMMMMMMHHHIIIIHHM:")
    print("		  :MMHIIIIIHMMMMMMMHHIIIIIIHHHMMMMMHHII:::IHM.")
    print("		   MH:I:::IHHMMMMMHHII:::IIHHMMMHHHMMM:I:IHMM")
    print("		   :MHI:HHIHMMHHIIHII::.::IIHMMHHIHHMMM::HMM:")
    print("		    MI::HHMMIIM:IIHII::..::HM:MHHII:::IHHMM:")
    print("		    MMMHII::..:::IHMMHHHMHHMMI:::...::IHM:")
    print("		    :MHHI::....::::HMMMMMMHHI::.. ..:::HM:")
    print("		     :MI:.:MH:.....:HMMMMHHMIHMMHHI:HH.:M")
    print("		     M:.I..MHHHHHMMMIHMMMMHMMHHHHHMMH:.:M.")
    print("		     M:.H..H  I:HM:MHMHI:IM:I:MM::  MMM:M:")
    print("		     :M:HM:.M I:MHMIIMMIIHM I:MM::.:MMI:M.")
    print("		     'M::MM:IMH:MMII MMHIMHI :M::IIHMM:MM")
    print("		      MH:HMMHIHMMMMMMHMMIMHIIHHHHIMMHHMM")
    print("		       MI:MMMMHI:::::IMM:MHI:::IMMMMHIM")
    print("			:IMHIHMMMMMM:MMMMMHHHHMMMHI:M")
    print("			 HI:IMIHMMMM:MMMMMMHHHMI:.:M	  .....")
    print("	     ............M::..:HMMMMIMHIIHMMMMHII:M:::''''")
    print("		 ....:::MHI:.:HMMMMMMMMHHHMHHI::M:::::::''''''")
    print("		''   ...:MHI:.::MMHHHMHMIHMMMMHH.MI..........")
    print("		   ''  ...MHI::.::MHHHHIHHMM:::IHM           '''")
    print("		      '  IMH.::..::HMMHMMMH::..:HM:")
    print("			:M:.H.IHMIIII::IIMHMMM:H.MH")
    print("			 IMMMH:HI:MMIMI:IHI:HIMIHM:")
    print("		       .MMI:.HIHMIMI:IHIHMMHIHI:MIM.")
    print("		      .MHI:::HHIIIIIHHI:IIII::::M:IM.")
    print("		     .MMHII:::IHIII::::::IIIIIIHMHIIM")
    print("		     MHHHI::.:IHHII:::.:::IIIIHMHIIHM:")
    print("		    MHHHII::..::MII::.. ..:IIIHHHII:IM.")
    print("		   .MHHII::....:MHII::.  .:IHHHI::IIHMM.")
    print("		   MMHHII::.....:IHMI:. ..:IHII::..:HHMM")
    print("		   MHHII:::......:IIHI...:IHI::.....::HM:")
    print("		  :MMH:::........ ...::..::....  ...:IHMM")
    print("		  IMHIII:::..........	  .........::IHMM.")
    print("		  :MHIII::::......	    .......::IHMM:")
    print("		   MHHIII::::...	     ......::IHMM:")
    print("		   IMHHIII:::...	     .....::IIHMM,")
    print("		   :MHHIII:::I:::...	 ....:::I:::IIHMM")
    print("		    MMHHIII::IHI:::...........:::IIH:IHMM")
    print("		    :MMHHII:IIHHI::::::.....:::::IH:IHMIM")
    print("		     MMMHHII:IIHHI:::::::::::::IHI:IIHM:M.")
    print("		     MMMHHIII::IHHII:::::::::IHI:IIIHMM:M:")
    print("		     :MMHHHIII::IIIHHII::::IHI..IIIHHM:MHM")
    print("		     :MMMHHII:..:::IHHMMHHHHI:IIIIHHMM:MIM")
    print("		     .MMMMHHII::.:IHHMM:::IIIIIIHHHMM:MI.M")
    print("		   .MMMMHHII::.:IHHMM:::IIIIIIHHHMM:MI.M")
    print("		 .MMMMHHMHHII:::IHHMM:::IIIIIHHHHMM:MI.IM.")
    print("		.MMHMMMHHHII::::IHHMM::I&&&IHHHHMM:MMH::IM.")
    print("	       .MMHHMHMHHII:::.::IHMM::IIIIHHHMMMM:MMH::IHM")
    print("	       :MHIIIHMMHHHII:::IIHMM::IIIHHMMMMM::MMMMHHHMM.")
    print("	       MMHI:IIHMMHHHI::::IHMM:IIIIHHHMMMM:MMMHI::IHMM.")
    print("	       MMH:::IHMMHHHHI:::IHMM:IIIHHHHMMMM:MMHI:.:IHHMM.")
    print("	       :MHI:::IHMHMHHII::IHMM:IIIHHHMMMMM:MHH::.::IHHM:")
    print("	       'MHHI::IHMMHMHHII:IHMM:IIHHHHMMMM:MMHI:...:IHHMM.")
    print("		:MHII:IIHMHIHHIIIIHMM:IIHHHHMMMM:MHHI:...:IIHMM:")
    print("		'MHIII:IHHMIHHHIIHHHMM:IHHHMMMMM:MHHI:..::IIHHM:")
    print("		 :MHHIIIHHMIIHHHIHHHMM:HHHHMMMMM:MHII::::IIIHHMM")
    print("		  MHHIIIIHMMIHHHIIHHMM:HHHHMMMM:MMHHIIHIIIIIHHMM.")
    print("		  'MHHIIIHHMIIHHIIIHMM:HHHMMMMH:MHHMHII:IIIHHHMM:")
    print("		   'MHHIIIHMMIHHHIHHMM:HHHMMMHH:MMIMMMHHHIIIHHMM:")
    print("		    'MHHIIHHMIHHHHHMMM:HHHMMMH:MIMMMMMMMMMMHIHHM:")
    print("		     'MHIIIHMMIHHHHHMM:HHHMMMH:IMMMMMHHIHHHMMHHM'")
    print("		      :MHHIIHMIHHHHHMM:HHHMMMM:MMHMMHIHMHI:IHHHM")
    print("		       MHHIIHM:HHHHHMM:HHHMMMM:MMMHIHHIHMM:HHIHM")
    print("			MHHIHM:IHHHHMM:HHHHMM:MMHMIIHMIMMMHMHIM:")
    print("			:MHIHMH:HHHHMM:HHHHMM:MMHIIHMIIHHMMHIHM:")
    print("			 MMHHMH:HHHHMM:HHHHMM:MHHIHMMIIIMMMIIHM'")
    print("			 'MMMMH:HHHHMM:HHHMM:MHHHIMMHIIII::IHM:")
    print("			  :MMHM:HHHHMM:HHHMM:MHIHIMMHHIIIIIHM:")
    print("			   MMMM:HHHHMM:HHHHM:MHHMIMMMHHHIHHM:MMMM.")
    print("			   :MMM:IHHHMM:HHHMM:MHHMIIMMMHHMM:MMMMMMM:")
    print("			   :MMM:IHHHM:HHHHMM:MMHHHIHHMMM:MMMMMMMMMM")
    print("			    MHM:IHHHM:HHHMMM:MMHHHHIIIMMIIMMMMMMMMM")
    print("			    MHM:HHHHM:HHHMMM:HMMHHHHHHHHHMMMMMMMMM:")
    print("			 .MI:MM:MHHMM:MHMMHMHHMMMMHHHHHHHMMMMMMMMM'")
    print("			:IM:MMIM:M:MM:MH:MM:MH:MMMMMHHHHHMMMMMMMM'")
    print("			:IM:M:IM:M:HM:IMIHM:IMI:MMMMMHHHMMMMMM:'")
    print("			 'M:MHM:HM:MN:HMIHM::M'   '::MMMMMMM:'")
    print("			    'M'HMM'M''M''HM'I'")

def charizard():
    print("                     .\"-,.__")
    print("                 `.     `.  ,")
    print("              .--'  .._,'\"-' `.")
    print("             .    .'         `'")
    print("             `.   /          ,'")
    print("               `  '--.   ,-\"'")
    print("                `\"`   |  \\")
    print("                   -. \, |")
    print("                    `--Y.'      ___.")
    print("                         \     L._, \\")
    print("               _.,        `.   <  <\                _")
    print("             ,' '           `, `.   | \            ( `")
    print("          ../, `.            `  |    .\`.           \ \_")
    print("         ,' ,..  .           _.,'    ||\l            )  '\".")
    print("        , ,'   \           ,'.-.`-._,'  |           .  _._`.")
    print("      ,' /      \ \        `' ' `--/   | \          / /   ..\\")
    print("    .'  /        \ .         |\__ - _ ,'` `        / /     `.`.")
    print("    |  '          ..         `-...-\"  |  `-'      / /        . `.")
    print("    | /           |L__           |    |          / /          `. `.")
    print("   , /            .   .          |    |         / /             ` `")
    print("  / /          ,. ,`._ `-_       |    |  _   ,-' /               ` \\")
    print(" / .           \"`_/. `-_ \_,.  ,'    +-' `-'  _,        ..,-.    \`.")
    print(".  '         .-f    ,'   `    '.       \__.---'     _   .'   '     \ \\")
    print("' /          `.'    l     .' /          \..      ,_|/   `.  ,'`     L`")
    print("|'      _.-""` `.    \ _,'  `            \ `.___`.'\"`-.  , |   |    | \\")
    print("||    ,'      `. `.   '       _,...._        `  |    `/ '  |   '     .|")
    print("||  ,'          `. ;.,.---' ,'       `.   `.. `-'  .-' /_ .'    ;_   ||")
    print("|| '              V      / /           `   | `   ,'   ,' '.    !  `. ||")
    print("||/            _,-------7 '              . |  `-'    l         /    `||")
    print(". |          ,' .-   ,' ||               | .-.        `.      .'     ||")
    print(" `'        ,'    `\".'    |               |    `.        '. -.'       `'")
    print("          /      ,'      |               |,'    \-.._,.'/'")
    print("          .     /        .               .       \    .''")
    print("        .`.    |         `.             /         :_,'.'")
    print("          \ `...\   _     ,'-.        .'         /_.-'")
    print("           `-.__ `,  `'   .  _.>----''.  _  __  /")
    print("                .'        /\"'          |  \"'   '_")
    print("               /_|.-'\ ,\".             '.'`__'-( \\")
    print("                 / ,\"'\"\,'               `/  `-.|\"")

charizard()

